import { FormEvent, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { GuideEditorNav } from "../components/GuideEditorNav";
import { StaffPageShell } from "../components/StaffPageShell";
import { createGuideLocation, deleteGuideLocation, listGuideLocations, updateGuideLocation } from "../data/locations";
import { getPaintGuide } from "../data/guides";
import type { GuideLocation, GuideLocationType, PaintGuide } from "../data/types";

const topTypes: GuideLocationType[] = ["floor", "structure", "exterior", "custom"];
const childTypes: GuideLocationType[] = ["room", "area", "custom"];
const label = (value: string) => value.charAt(0).toUpperCase() + value.slice(1);

function LocationForm({ guideId, parent, sortOrder, onCreated, onCancel }: { guideId: string; parent: GuideLocation | null; sortOrder: number; onCreated: (location: GuideLocation) => void; onCancel: () => void }) {
  const [name, setName] = useState(""); const [type, setType] = useState<GuideLocationType>(parent ? "room" : "floor"); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  const options = parent ? childTypes : topTypes;
  async function submit(e: FormEvent) { e.preventDefault(); const trimmed = name.trim(); if (!trimmed) { setError("Location name is required."); return; } setPending(true); setError(""); try { onCreated(await createGuideLocation({ guideId, parentId: parent?.id ?? null, locationType: type, name: trimmed, sortOrder })); } catch { setError("Could not add location. Please try again."); setPending(false); } }
  return <form className="mt-4 border border-[#20211f]/15 bg-[#fffdf8] p-4" onSubmit={(e) => void submit(e)}><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Name<input autoFocus className="mt-1 w-full border border-[#20211f]/25 bg-white px-3 py-2" disabled={pending} onChange={(e) => setName(e.target.value)} value={name} /></label><label className="text-sm font-semibold">Type<select className="mt-1 w-full border border-[#20211f]/25 bg-white px-3 py-2" disabled={pending} onChange={(e) => setType(e.target.value as GuideLocationType)} value={type}>{options.map((o) => <option key={o} value={o}>{label(o)}</option>)}</select></label></div>{error ? <p className="mt-3 text-sm text-[#9c2f2f]" role="alert">{error}</p> : null}<div className="mt-4 flex gap-3"><button className="bg-[#20211f] px-4 py-2 text-xs font-semibold uppercase tracking-[0.12em] text-white disabled:opacity-60" disabled={pending} type="submit">{pending ? "Adding…" : "Add Location"}</button><button className="text-xs font-semibold uppercase tracking-[0.12em]" disabled={pending} onClick={onCancel} type="button">Cancel</button></div></form>;
}

function LocationItem({ location, children, guideId, onUpdate, onDelete }: { location: GuideLocation; children: GuideLocation[]; guideId: string; onUpdate: (next: GuideLocation) => void; onDelete: (id: string) => void }) {
  const [mode, setMode] = useState<"view" | "add" | "edit" | "confirm">("view"); const [name, setName] = useState(location.name); const [type, setType] = useState<GuideLocationType>(location.location_type); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const isTop = !location.parent_id; const options = isTop ? topTypes : childTypes;
  async function save(e: FormEvent) { e.preventDefault(); const trimmed = name.trim(); if (!trimmed) { setError("Location name is required."); return; } setPending(true); try { onUpdate(await updateGuideLocation(guideId, location.id, { name: trimmed, locationType: type })); setMode("view"); } catch { setError("Could not save location. Please try again."); } finally { setPending(false); } }
  async function remove() { setPending(true); try { await deleteGuideLocation(guideId, location.id); onDelete(location.id); } catch { setError("Could not delete location. Please try again."); setMode("view"); setPending(false); } }
  return <li className={isTop ? "border border-[#20211f]/15 bg-white p-5" : "ml-5 border-l border-[#20211f]/15 pl-5"}>{mode === "edit" ? <form onSubmit={(e) => void save(e)}><div className="grid gap-3 sm:grid-cols-2"><input className="border border-[#20211f]/25 px-3 py-2" disabled={pending} onChange={(e) => setName(e.target.value)} value={name}/><select className="border border-[#20211f]/25 px-3 py-2" disabled={pending} onChange={(e) => setType(e.target.value as GuideLocationType)} value={type}>{options.map((o) => <option key={o} value={o}>{label(o)}</option>)}</select></div>{error ? <p className="mt-2 text-sm text-[#9c2f2f]">{error}</p> : null}<div className="mt-3 flex gap-3"><button className="text-xs font-semibold uppercase tracking-[0.12em]" disabled={pending} type="submit">{pending ? "Saving…" : "Save"}</button><button className="text-xs font-semibold uppercase tracking-[0.12em]" onClick={() => setMode("view")} type="button">Cancel</button></div></form> : <><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-serif text-xl">{location.name}</p><p className="mt-1 text-xs uppercase tracking-[0.14em] text-[#20211f]/50">{label(location.location_type)}</p></div><div className="flex gap-3 text-xs font-semibold uppercase tracking-[0.12em]"><button onClick={() => setMode("edit")} type="button">Edit</button>{isTop ? <button onClick={() => setMode("add")} type="button">Add Room / Area</button> : null}<button className="text-[#9c2f2f]" onClick={() => setMode("confirm")} type="button">Delete</button></div></div>{mode === "confirm" ? <div className="mt-4 border-t border-[#9c2f2f]/20 pt-4 text-sm">{isTop ? "Deleting this location will also delete its nested locations. " : ""}Are you sure? <button className="ml-3 font-semibold text-[#9c2f2f]" disabled={pending} onClick={() => void remove()} type="button">{pending ? "Deleting…" : "Delete"}</button><button className="ml-3" onClick={() => setMode("view")} type="button">Cancel</button></div> : null}{mode === "add" ? <LocationForm guideId={guideId} onCancel={() => setMode("view")} onCreated={onUpdate} parent={location} sortOrder={children.length * 10} /> : null}</>}{children.length ? <ul className="mt-5 space-y-4">{children.map((child) => <LocationItem children={[]} guideId={guideId} key={child.id} location={child} onDelete={onDelete} onUpdate={onUpdate} />)}</ul> : null}</li>;
}

export function GuideLocations() {
  const { guideId = "" } = useParams(); const [guide, setGuide] = useState<PaintGuide | null>(null); const [locations, setLocations] = useState<GuideLocation[]>([]); const [state, setState] = useState<"loading" | "ready" | "not_found" | "error">("loading"); const [adding, setAdding] = useState(false);
  useEffect(() => { let active=true; Promise.all([getPaintGuide(guideId), listGuideLocations(guideId)]).then(([nextGuide, nextLocations]) => { if(!active)return; if(!nextGuide){setState("not_found");return;} setGuide(nextGuide);setLocations(nextLocations);setState("ready"); }).catch(() => active && setState("error")); return () => {active=false;}; }, [guideId]);
  const upsert=(next:GuideLocation)=>setLocations((current)=>{const exists=current.some((item)=>item.id===next.id); const result=exists?current.map((item)=>item.id===next.id?next:item):[...current,next]; return result.sort((a,b)=>a.sort_order-b.sort_order||a.created_at.localeCompare(b.created_at));}); const remove=(id:string)=>setLocations((current)=>{const removed=new Set<string>([id]); let changed=true; while(changed){changed=false; current.forEach((item)=>{if(item.parent_id&&removed.has(item.parent_id)&&!removed.has(item.id)){removed.add(item.id);changed=true;}});} return current.filter((item)=>!removed.has(item.id));});
  if(state === "loading") return <StaffPageShell title="Paint Guide"><p className="py-12 text-sm uppercase tracking-[0.14em] text-[#20211f]/60">Loading locations…</p></StaffPageShell>;
  if(state !== "ready") return <StaffPageShell title="Paint Guide"><section className="py-12"><h2 className="font-serif text-3xl">Paint Guide not found</h2><Link className="mt-6 inline-flex border border-[#20211f] px-4 py-3 text-xs font-semibold uppercase tracking-[0.12em]" to="/paint-guide">Back to Paint Guides</Link></section></StaffPageShell>;
  const tops=locations.filter((l)=>!l.parent_id); return <StaffPageShell title={guide?.residence_name ?? "Paint Guide"}><GuideEditorNav active="locations"/><section className="py-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#9b6b36]">Locations</p><h2 className="mt-3 font-serif text-3xl">Residence hierarchy</h2></div><button className="bg-[#20211f] px-4 py-3 text-xs font-semibold uppercase tracking-[0.12em] text-white" onClick={()=>setAdding((v)=>!v)} type="button">Add Location</button></div>{adding ? <LocationForm guideId={guideId} onCancel={()=>setAdding(false)} onCreated={(next)=>{upsert(next);setAdding(false);}} parent={null} sortOrder={tops.length * 10} /> : null}{tops.length===0 ? <div className="mt-8 max-w-2xl border border-[#20211f]/15 bg-white p-8"><h3 className="font-serif text-2xl">No locations yet.</h3><p className="mt-3 text-[#20211f]/65">Start by adding the floors or major structures for this residence.</p></div> : <ul className="mt-8 space-y-5">{tops.map((top)=><LocationItem children={locations.filter((item)=>item.parent_id===top.id)} guideId={guideId} key={top.id} location={top} onDelete={remove} onUpdate={upsert}/>)}</ul>}</section></StaffPageShell>;
}
