import { FormEvent,useEffect,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { GuideEditorNav } from "../components/GuideEditorNav";
import { StaffPageShell } from "../components/StaffPageShell";
import { createPaintRecord,deletePaintRecord,listPaintRecords,updatePaintRecord,type PaintRecordInput } from "../data/paint-records";
import { getPaintGuide } from "../data/guides";
import type { PaintGuide,PaintRecord,PaintRecordSection } from "../data/types";
const sections:PaintRecordSection[]=["primary","exception","additional"]; const heading=(s:PaintRecordSection)=>s==="primary"?"Primary":s==="exception"?"Exceptions":"Additional";
const blank=():PaintRecordInput=>({section:"primary",surface:"",colorName:"",brand:"",product:"",colorCode:"",sheen:"",notes:"",sortOrder:0});
function Form({initial,onSave,onCancel,pending}:{initial:PaintRecordInput;onSave:(v:PaintRecordInput)=>Promise<void>;onCancel:()=>void;pending:boolean}){const[v,setV]=useState(initial);const[e,setE]=useState("");const field=(key:keyof PaintRecordInput,label:string,required=false)=><label className="text-sm font-semibold">{label}<input className="mt-1 w-full border border-[#20211f]/25 px-3 py-2" required={required} value={v[key] as string} onChange={x=>setV({...v,[key]:x.target.value})}/></label>;return <form className="mt-5 grid gap-3 border border-[#20211f]/15 bg-white p-5 sm:grid-cols-2" onSubmit={async x=>{x.preventDefault();if(!v.surface.trim()||!v.colorName.trim()){setE("Surface and Color Name are required.");return;}await onSave(v);}}><label>Section<select className="mt-1 w-full border border-[#20211f]/25 px-3 py-2" value={v.section} onChange={x=>setV({...v,section:x.target.value as PaintRecordSection})}>{sections.map(s=><option key={s} value={s}>{heading(s)}</option>)}</select></label>{field("surface","Surface",true)}{field("colorName","Color Name",true)}{field("brand","Brand")}{field("product","Product")}{field("colorCode","Color Code")}{field("sheen","Sheen")}<label className="sm:col-span-2">Notes<textarea className="mt-1 w-full border border-[#20211f]/25 px-3 py-2" value={v.notes} onChange={x=>setV({...v,notes:x.target.value})}/></label>{e?<p role="alert" className="text-sm text-[#9c2f2f]">{e}</p>:null}<div className="flex gap-3"><button disabled={pending} className="bg-[#20211f] px-4 py-2 text-xs font-semibold uppercase tracking-[.12em] text-white">{pending?"Saving…":"Save"}</button><button type="button" disabled={pending} onClick={onCancel}>Cancel</button></div></form>}
export function GuideColors(){const{guideId=""}=useParams();const[g,setG]=useState<PaintGuide|null>(null),[r,setR]=useState<PaintRecord[]>([]),[state,setState]=useState("loading"),[add,setAdd]=useState(false),[edit,setEdit]=useState<string|null>(null),[del,setDel]=useState<string|null>(null),[pending,setPending]=useState(false);useEffect(()=>{let a=true;Promise.all([getPaintGuide(guideId),listPaintRecords(guideId)]).then(([guide,records])=>{if(!a)return;if(!guide)setState("notfound");else{setG(guide);setR(records);setState("ready")}}).catch(()=>a&&setState("error"));return()=>{a=false}},[guideId]);const save=async(v:PaintRecordInput,id?:string)=>{setPending(true);try{const target=id?await updatePaintRecord(guideId,id,v):await createPaintRecord(guideId,{...v,sortOrder:(r.filter(x=>x.section===v.section).reduce((m,x)=>Math.max(m,x.sort_order),-10)+10)});setR(x=>id?x.map(y=>y.id===id?target:y):[...x,target]);setAdd(false);setEdit(null)}catch{}finally{setPending(false)}};if(state!=="ready")return <StaffPageShell title="Paint Guide"><p className="py-12">{state==="error"?"Could not load colors. Please try again.":"Paint Guide not found"}</p></StaffPageShell>;return <StaffPageShell title={g!.residence_name}><GuideEditorNav active="colors"/><section className="py-10"><button className="bg-[#20211f] px-4 py-3 text-xs font-semibold uppercase tracking-[.12em] text-white" onClick={()=>setAdd(true)}>Add Paint Record</button>{add?<Form initial={blank()} onCancel={()=>setAdd(false)} onSave={save} pending={pending}/>:null}{r.length===0?<p className="mt-8">No paint records yet. Add the primary paint specifications for this residence.</p>:sections.map(s=><div className="mt-10" key={s}><h2 className="font-serif text-3xl">{heading(s)}</h2>{s==="primary"&&g?.primary_scope_note?<p className="mt-2 text-[#20211f]/65">{g.primary_scope_note}</p>:null}{r.filter(x=>x.section===s).map(x=><article className="mt-4 border border-[#20211f]/15 bg-white p-5" key={x.id}>{edit===x.id?<Form initial={{section:x.section,surface:x.surface,colorName:x.color_name,brand:x.brand??"",product:x.product??"",colorCode:x.color_code??"",sheen:x.sheen??"",notes:x.notes??"",sortOrder:x.sort_order}} onCancel={()=>setEdit(null)} onSave={v=>save(v,x.id)} pending={pending}/>:<><h3 className="font-serif text-xl">{x.surface}</h3><p>{x.color_name}{x.sheen?` · ${x.sheen}`:""}</p>{[x.brand,x.product,x.color_code,x.notes].filter(Boolean).map((v,i)=><p className="text-sm text-[#20211f]/65" key={i}>{v}</p>)}<button onClick={()=>setEdit(x.id)}>Edit</button><button className="ml-4 text-[#9c2f2f]" onClick={()=>setDel(x.id)}>Delete</button>{del===x.id?<p>Delete this Paint Record? <button disabled={pending} onClick={async()=>{setPending(true);try{await deletePaintRecord(guideId,x.id);setR(y=>y.filter(z=>z.id!==x.id));setDel(null)}finally{setPending(false)}}}>Delete</button><button onClick={()=>setDel(null)}>Cancel</button></p>:null}</>}</article>)}</div>)}</section></StaffPageShell>}
