import { ArrowUpRight, ChevronRight } from "lucide-react";
import { Link } from "react-router-dom";

type LocationConfig = {
  city: string; slug: string; hero: string; introEyebrow: string; introTitle: string; intro: string;
  detailEyebrow: string; detailTitle: string; detail: string; processTitle: string; process: string;
  image: string; imageAlt: string; secondaryImage: string; secondaryAlt: string; variant: "dark" | "light" | "split" | "editorial";
};

export const remainingLocationConfigs: Record<string, LocationConfig> = {
  alpine: { city: "Alpine", slug: "alpine", variant: "dark", hero: "The detail is the architecture.", introEyebrow: "Refined interior finish work", introTitle: "Quiet surfaces. Exacting standards.", intro: "Tauro serves Alpine custom homes and premium residential projects with interior painting, cabinetry, doors, trim, and architectural woodwork finished with disciplined surface preparation and restrained detailing.", detailEyebrow: "The close work", detailTitle: "Cabinetry, doors, trim, and the lines between them.", detail: "Premium interior painting depends on the small relationships between materials: an enamelled cabinet, a stained door, a clear-finished wood detail, or trim meeting a wall. Each needs its own preparation and finish system.", processTitle: "Detail work belongs in the sequence.", process: "We coordinate with builders and designers around protected application, material-specific finish work, and final punch so the details remain as deliberate at handoff as they were in the plan.", image: "/tauro/interior-living.webp", imageAlt: "Tauro Painting refined custom-home interior finish work", secondaryImage: "/tauro/stair-detail.webp", secondaryAlt: "Tauro Painting architectural stair and trim finish detail" },
  highland: { city: "Highland", slug: "highland", variant: "light", hero: "One finish package. One standard.", introEyebrow: "A coordinated finish package", introTitle: "The whole home should read as one decision.", intro: "Tauro serves Highland custom-home projects by coordinating interior and exterior painting, cabinetry, wood finishes, and transitions between finish systems as one considered package rather than separate trades.", detailEyebrow: "Continuity across surfaces", detailTitle: "From the exterior system to the last interior detail.", detail: "Painted walls, exterior coatings, cabinetry, stain, clear finishes, doors, and architectural woodwork all carry the finish language of a home. Consistency comes from treating the systems as related work.", processTitle: "Coordination that holds the finish together.", process: "We work alongside builders and designers to plan preparation, protect completed surfaces, sequence applications, and resolve final punch without breaking the continuity of the completed home.", image: "/tauro/exterior-residence.webp", imageAlt: "Tauro Painting exterior finish work on a custom residence", secondaryImage: "/tauro/office-woodwork.webp", secondaryAlt: "Tauro Painting cabinetry and architectural woodwork finish detail" },
  mapleton: { city: "Mapleton", slug: "mapleton", variant: "split", hero: "The material sets the method.", introEyebrow: "Material-specific finishing", introTitle: "A finish system should respect what it covers.", intro: "Tauro serves Mapleton custom homes with premium paint systems, stain, clear finishes, cabinetry, doors, trim, and natural wood details—each approached through the preparation and application its material requires.", detailEyebrow: "No one-size-fits-all finish", detailTitle: "Stain, clear coat, enamel, paint: each surface has its own demand.", detail: "Natural wood, cabinetry, architectural millwork, doors, and painted surfaces respond differently to light, substrate, sheen, and protection. The right result starts with choosing the right finish process.", processTitle: "Preparation is part of the material conversation.", process: "We coordinate with builders and designers from surface correction through protected application and final punch, making room for each material to be finished at the right stage.", image: "/tauro/woodwork-detail.webp", imageAlt: "Tauro Painting woodwork and clear finish detail", secondaryImage: "/tauro/entry-door.webp", secondaryAlt: "Tauro Painting stained door finish detail" },
  lehi: { city: "Lehi", slug: "lehi", variant: "editorial", hero: "The schedule is part of the finish.", introEyebrow: "Sequencing with intent", introTitle: "Finish work has a right time to happen.", intro: "Tauro serves Lehi custom-home and premium residential projects with a finish process built around timing: detailed preparation, protected application, cabinetry, interior and exterior painting, and final punch coordinated around the other trades.", detailEyebrow: "Work that respects the build", detailTitle: "Preparation, protection, and application at the right moment.", detail: "Premium finishes need space to be corrected, applied, and protected. Interior painting, exterior systems, cabinetry, stain, clear finishes, doors, and trim all depend on a sequence that protects completed work.", processTitle: "From early prep to final punch.", process: "We coordinate with builders and designers through the stages of the project, helping avoid late-stage conflicts and keeping the handoff clean, considered, and ready for close review.", image: "/tauro/interior-open-plan.webp", imageAlt: "Tauro Painting custom-home interior finish work", secondaryImage: "/tauro/exterior-custom-home.webp", secondaryAlt: "Tauro Painting exterior finish work on a custom home" },
  "pleasant-grove": { city: "Pleasant Grove", slug: "pleasant-grove", variant: "light", hero: "The surface earns the finish.", introEyebrow: "Preparation and finish quality", introTitle: "The work beneath the coating is what holds up.", intro: "Tauro serves Pleasant Grove custom homes and premium residential projects with detailed surface correction, protection, premium coatings, and final inspection for interiors, exteriors, cabinetry, and architectural details.", detailEyebrow: "A disciplined first pass", detailTitle: "Correct, protect, then finish.", detail: "Clean transitions and refined results come from attention before the visible coat: substrate conditions, sanding, filling, caulking, masking, and protection of the surfaces already complete.", processTitle: "A finish standard that makes room for inspection.", process: "We coordinate with builders and designers through preparation, application, and final punch, reviewing the details so completed surfaces are ready for a clean handoff.", image: "/tauro/coffered-ceiling.webp", imageAlt: "Tauro Painting detailed custom-home ceiling finish", secondaryImage: "/tauro/interior-great-room.webp", secondaryAlt: "Tauro Painting custom-home interior finish work" },
  "cedar-hills": { city: "Cedar Hills", slug: "cedar-hills", variant: "dark", hero: "A finish that carries through.", introEyebrow: "Exterior to interior continuity", introTitle: "The exterior system is only the first transition.", intro: "Tauro serves Cedar Hills projects with exterior painting and finish systems that connect cleanly to doors, trim, interior finishes, protection, and refined final detailing across the home.", detailEyebrow: "Transitions, protected", detailTitle: "From exterior coatings to the interior details that follow.", detail: "Exterior surfaces, entry doors, trim, premium interior painting, cabinetry, stain, and clear finishes meet at points that require close preparation and a controlled finish process.", processTitle: "Protection keeps the details intact.", process: "We work with builders and designers to sequence applications, protect adjacent completed materials, and return for final detailing when the project is ready for handoff.", image: "/tauro/exterior-custom-home.webp", imageAlt: "Tauro Painting exterior finish system on a custom home", secondaryImage: "/tauro/entry-door.webp", secondaryAlt: "Tauro Painting door and clear finish detail" },
  "woodland-hills": { city: "Woodland Hills", slug: "woodland-hills", variant: "split", hero: "The materials should speak together.", introEyebrow: "Woodwork and painted surfaces", introTitle: "Character lives in the relationship between materials.", intro: "Tauro serves Woodland Hills custom-home projects with wood finishes, clear finishes, cabinetry, architectural woodwork, and premium painted surfaces designed to read together without attaching unverified local project claims.", detailEyebrow: "A complete material language", detailTitle: "Wood, cabinetry, paint, and the transitions between them.", detail: "Stain and clear finishes bring out the character of natural wood; cabinetry and painted surfaces need their own controlled systems. The result depends on preparation and application that respect each material.", processTitle: "Finish systems with a shared standard.", process: "We coordinate with builders and designers around timing, protection, and final punch so woodwork, cabinetry, interior painting, and exterior details arrive at a consistent completed standard.", image: "/tauro/office-woodwork.webp", imageAlt: "Tauro Painting cabinetry and architectural woodwork finish detail", secondaryImage: "/tauro/woodwork-detail.webp", secondaryAlt: "Tauro Painting stained wood and clear finish detail" },
  "elk-ridge": { city: "Elk Ridge", slug: "elk-ridge", variant: "editorial", hero: "The final standard should hold together.", introEyebrow: "Whole-home finish consistency", introTitle: "From the first completed surface to the final punch-list detail.", intro: "Tauro serves Elk Ridge custom homes and premium residential projects with coordinated interiors, exteriors, cabinetry, woodwork, and touch-ups that keep the finish quality consistent through final handoff.", detailEyebrow: "One completed home", detailTitle: "Interiors, exteriors, cabinetry, and woodwork in conversation.", detail: "Premium finish quality is not a collection of isolated surfaces. It is a consistent approach to preparation, paint systems, stain and clear finishes, protection, and the details that connect the completed home.", processTitle: "Final punch is part of the craft.", process: "We coordinate with builders and designers to protect completed work, resolve touch-ups, and close the handoff with the same care given to the first finish pass.", image: "/tauro/interior-great-room.webp", imageAlt: "Tauro Painting custom-home interior finish work", secondaryImage: "/tauro/exterior-residence.webp", secondaryAlt: "Tauro Painting exterior finish work on a custom residence" },
};

const eyebrow = "text-xs font-semibold uppercase tracking-[0.24em]";
const heading = "text-4xl font-semibold leading-[1.08] tracking-[-0.04em] sm:text-5xl";
const link = "inline-flex min-h-11 items-center gap-4 border-b border-current py-2 text-xs font-semibold uppercase tracking-[0.14em] transition-colors hover:text-[#9a6a25] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4";

export default function RemainingLocationPage({ location }: { location: keyof typeof remainingLocationConfigs }) {
  const c = remainingLocationConfigs[location]; const darkHero = c.variant === "dark" || c.variant === "editorial"; const imageFirst = c.variant === "split" || c.variant === "editorial";
  return <div>
    <section aria-labelledby={`${c.slug}-heading`} className={darkHero ? "bg-slate-950 text-white" : "bg-[#f5f3ee] text-slate-950"}>
      <div className="mx-auto max-w-7xl px-6 pb-10 pt-8 lg:px-8 lg:pt-10"><nav aria-label="Breadcrumb" className={`flex flex-wrap items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] ${darkHero ? "text-white/55" : "text-slate-500"}`}><Link to="/" className="transition-colors hover:text-current">Home</Link><ChevronRight aria-hidden="true" className="h-3 w-3" /><Link to="/locations" className="transition-colors hover:text-current">Where Tauro works</Link><ChevronRight aria-hidden="true" className="h-3 w-3" /><span aria-current="page" className="text-[#c5a374]">{c.city}, Utah</span></nav></div>
      <div className="mx-auto grid max-w-7xl gap-12 px-6 pb-16 lg:grid-cols-12 lg:items-end lg:gap-16 lg:px-8 lg:pb-24"><div className="lg:col-span-8"><p className={`${eyebrow} mb-7 flex items-center gap-3 text-[#c5a374]`}><span aria-hidden="true" className="h-px w-8 bg-[#a64036]" />{c.city}, Utah</p><h1 id={`${c.slug}-heading`} className="max-w-4xl text-5xl font-semibold leading-[0.98] tracking-[-0.05em] sm:text-7xl lg:text-[5.7rem]">{c.hero}</h1></div><div className="lg:col-span-4 lg:pb-1"><p className={`text-lg leading-8 ${darkHero ? "text-white/75" : "text-slate-600"}`}>Premium custom-home painting and finishing for {c.city} projects where the finish sequence and final details deserve close attention.</p><Link to="/contact" className={`${link} mt-7`}>Request a walkthrough <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></div></div>
    </section>
    <section aria-labelledby={`${c.slug}-intro-heading`} className={imageFirst ? "bg-white py-20 lg:py-28" : "bg-[#f5f3ee] py-20 lg:py-28"}><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-12 lg:items-center lg:gap-16 lg:px-8">{imageFirst && <figure className="lg:col-span-6"><img src={c.image} alt={c.imageAlt} fetchPriority="high" className="aspect-[5/4] w-full object-cover" /><figcaption className="mt-4 text-[10px] uppercase tracking-[0.18em] text-slate-500">Real Tauro work · finish detail</figcaption></figure>}<div className={imageFirst ? "lg:col-span-5 lg:col-start-8" : "lg:col-span-8 lg:col-start-5"}><p className={`${eyebrow} mb-6 text-[#9a6a25]`}>{c.introEyebrow}</p><h2 id={`${c.slug}-intro-heading`} className={`${heading} max-w-3xl text-slate-950`}>{c.introTitle}</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">{c.intro}</p></div>{!imageFirst && <figure className="lg:col-span-7 lg:col-start-4"><img src={c.image} alt={c.imageAlt} loading="lazy" className="mt-8 aspect-[16/8] w-full object-cover" /></figure>}</div></section>
    <section aria-labelledby={`${c.slug}-detail-heading`} className={c.variant === "light" ? "bg-slate-950 py-20 text-white lg:py-28" : "bg-white py-20 lg:py-28"}><div className="mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-12 lg:items-center lg:gap-16 lg:px-8"><div className="lg:col-span-5"><p className={`${eyebrow} mb-6 ${c.variant === "light" ? "text-[#c5a374]" : "text-[#9a6a25]"}`}>{c.detailEyebrow}</p><h2 id={`${c.slug}-detail-heading`} className={`${heading} ${c.variant === "light" ? "text-white" : "text-slate-950"}`}>{c.detailTitle}</h2><p className={`mt-7 leading-8 ${c.variant === "light" ? "text-white/70" : "text-slate-600"}`}>{c.detail}</p><Link to="/services" className={`${link} mt-8`}>Explore finishing services <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></div><figure className="lg:col-span-7"><img src={c.secondaryImage} alt={c.secondaryAlt} loading="lazy" className="aspect-[5/4] w-full object-cover lg:aspect-[16/10]" /></figure></div></section>
    <section aria-labelledby={`${c.slug}-process-heading`} className={c.variant === "light" ? "bg-[#f5f3ee] py-20 lg:py-28" : "bg-slate-950 py-20 text-white lg:py-28"}><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-7"><p className={`${eyebrow} mb-6 ${c.variant === "light" ? "text-[#9a6a25]" : "text-[#c5a374]"}`}>Builder &amp; designer coordination</p><h2 id={`${c.slug}-process-heading`} className={`${heading} max-w-3xl ${c.variant === "light" ? "text-slate-950" : "text-white"}`}>{c.processTitle}</h2></div><p className={`leading-8 lg:col-span-4 lg:col-start-9 ${c.variant === "light" ? "text-slate-600" : "text-white/70"}`}>{c.process}</p></div><div className={`mt-14 grid border-t ${c.variant === "light" ? "border-slate-300" : "border-white/20"} md:grid-cols-3`}>{["Prepare deliberately", "Protect the progress", "Close with care"].map((step, index) => <div key={step} className={`border-b py-8 md:border-b-0 md:py-10 md:pr-8 md:[&:not(:last-child)]:border-r md:[&:not(:first-child)]:pl-8 ${c.variant === "light" ? "border-slate-300" : "border-white/20"}`}><p className={`text-[10px] font-semibold tracking-[0.2em] ${c.variant === "light" ? "text-[#9a6a25]" : "text-[#c5a374]"}`}>0{index + 1}</p><h3 className={`mt-5 text-2xl font-semibold tracking-[-0.03em] ${c.variant === "light" ? "text-slate-950" : "text-white"}`}>{step}</h3></div>)}</div></div></section>
    <section aria-labelledby={`${c.slug}-work-heading`} className="bg-white py-20 lg:py-28"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-10 px-6 lg:flex-row lg:items-end lg:px-8"><div><p className={`${eyebrow} mb-5 text-[#9a6a25]`}>See the finish language</p><h2 id={`${c.slug}-work-heading`} className={`${heading} max-w-2xl text-slate-950`}>Real work, without invented labels.</h2><p className="mt-7 max-w-2xl leading-8 text-slate-600">Explore Tauro&apos;s selected work across interiors, exteriors, cabinetry, woodwork, stain, and clear finishes—presented without unverified {c.city} project names or locations.</p></div><div className="flex flex-col items-start gap-5"><Link to="/projects" className="inline-flex min-h-14 items-center gap-5 bg-slate-950 px-6 py-4 text-xs font-semibold uppercase tracking-[0.12em] text-white transition-colors hover:bg-[#9a6a25]">View selected work <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link><Link to="/locations" className={`${link} text-slate-950`}>Where Tauro works <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></div></div></section>
    <section aria-labelledby={`${c.slug}-cta-heading`} className="bg-[#f5f3ee] py-20 lg:py-28"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-10 px-6 lg:flex-row lg:items-end lg:px-8"><div><p className={`${eyebrow} mb-5 text-[#9a6a25]`}>Start with the walkthrough</p><h2 id={`${c.slug}-cta-heading`} className={`${heading} max-w-2xl text-slate-950`}>Let&apos;s walk the project before the details get expensive.</h2></div><Link to="/contact" className="inline-flex min-h-14 w-full items-center justify-center gap-5 bg-slate-950 px-6 py-4 text-xs font-semibold uppercase tracking-[0.12em] text-white transition-colors hover:bg-[#9a6a25] lg:w-auto">Request a walkthrough <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></div></section>
  </div>;
}
